# Generated by Django 5.0.3 on 2024-05-26 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderitemstable",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="orderstatustable",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="ordertable",
            options={"managed": False},
        ),
    ]
