# Generated by Django 5.0.3 on 2024-07-14 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_alter_orderitemstable_options_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="orderitemstable",
            table="tblOrderItem",
        ),
        migrations.AlterModelTable(
            name="orderstatustable",
            table="tblOrderStatuses",
        ),
        migrations.AlterModelTable(
            name="ordertable",
            table="tblOrders",
        ),
    ]
