# Generated by Django 5.0.7 on 2024-07-14 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PaymentMethod",
        ),
        migrations.DeleteModel(
            name="PaymentStatus",
        ),
        migrations.DeleteModel(
            name="Purchase",
        ),
    ]
