# Generated by Django 5.0.3 on 2024-05-26 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paymentmethod",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="paymentstatus",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="purchase",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="useraddresstable",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="usertable",
            options={"managed": False},
        ),
    ]

