# Generated by Django 5.0.3 on 2024-07-14 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_paymentmethod_options_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="paymentmethod",
            table="tblPaymentMethods",
        ),
        migrations.AlterModelTable(
            name="paymentstatus",
            table="tblPaymentStatuses",
        ),
        migrations.AlterModelTable(
            name="purchase",
            table="tblPurchase",
        ),
        migrations.AlterModelTable(
            name="useraddresstable",
            table="tblAddresses",
        ),
        migrations.AlterModelTable(
            name="usertable",
            table="tblUsers",
        ),
    ]
