# Generated by Django 5.0.3 on 2024-05-26 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productdetails_productimage_productvariant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='productdetails',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='productsubcategory',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'managed': False},
        ),
    ]
