# Generated by Django 4.0 on 2024-05-26 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "customer_id",
                    models.AutoField(
                        db_column="custIdpk", primary_key=True, serialize=False
                    ),
                ),
            ],
            options={
                "db_table": "tblCustomers",
                "managed": False,
            },
        ),
    ]
