# Generated by Django 5.0.3 on 2024-05-25 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0003_productdetails_productimage_productvariant'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('invIdpk', models.AutoField(primary_key=True, serialize=False)),
                ('invQuantityAvailable', models.IntegerField()),
                ('invUnitPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invUnitCost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invDateAdded', models.DateTimeField()),
                ('invExpirationDate', models.DateTimeField()),
                ('invLastUpdateDate', models.DateTimeField(auto_now=True)),
                ('invPrdIdfk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('invSupIdfk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.suppliertable')),
            ],
        ),
    ]
