# Generated by Django 5.0.3 on 2024-05-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('crtIdpk', models.AutoField(primary_key=True, serialize=False)),
                ('crtCreatedAt', models.DateTimeField(auto_now_add=True)),
                ('crtStatus', models.CharField(default='Active', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('crtItemIdpk', models.AutoField(primary_key=True, serialize=False)),
                ('crtItemQuantity', models.IntegerField()),
                ('crtItemUnitPrice', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
