# Generated by Django 5.0.3 on 2024-05-25 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
        ('customer', '0001_initial'),
        ('product', '0003_productdetails_productimage_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='crtCustomerIdfk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customertable'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='crtItemCrtIdfk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cart'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='crtItemPrdIdfk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
