# Generated by Django 5.0.3 on 2024-07-14 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_options_alter_cartitem_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table='tblCarts',
        ),
        migrations.AlterModelTable(
            name='cartitem',
            table='tblCartItems',
        ),
    ]
